apiVersion: broker.amq.io/v1beta1
kind: ActiveMQArtemisApp
metadata:
  name: wq-app
spec:
  acceptor:
    port: 61616
  capabilities: [
    producerOf: [
      address: APP.JOBS
    ]
  ]
  selector:
    matchLabels:
      forWorkQueue: 'true'
status:
  conditions: []